### ISSUE TITLE
[PE-D] addsg bug in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-1/tp#182]
In the UG, the parameter `gn` is used, but in the example `g` is used

![image.png](https://raw.githubusercontent.com/Cyn7hius/ped/main/files/2c5b7d71-fed4-453d-bf92-239736abe87d.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Cyn7hius/ped#8

**Comment by rushilramesh** [comment]
Update UG. However, severity is clearly not high (minor typo)  and it is a documentation bug not a feature flaw. Not sure what the reviewer was smoking when he was reviewing the UG 🥴
