### ISSUE TITLE
[PE-D] Potential bug in adding student to tutorial class

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-1/tp#185]
The default class is G00 for the people in the sample data. However, adding them to a new tutorial class `g06` does not change it, not sure if it is by design or its a bug. Maybe can show G00 in the tutorial classes to let users know that they already belong to a tutorial group 

![image.png](https://raw.githubusercontent.com/Cyn7hius/ped/main/files/a1777226-70b8-4b64-8f57-e618949348d9.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Cyn7hius/ped#9

**Comment by rushilramesh** [comment]
Include in UG `G00` invlaid command 
- addc section
- addcg seciton
- editstu section (optional, more for implementation)

Update implementation to safeguard against `g00` inputs
