### ISSUE TITLE
[PE-D] Unable to add student despite example given.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-1/tp#189]
![image.png](https://raw.githubusercontent.com/idgrr/ped/main/files/a74d8921-45df-4a73-858e-da0ffb24a66d.png)

Unable to add person even though it was the example within the UG

![image.png](https://raw.githubusercontent.com/idgrr/ped/main/files/f76c4737-4457-494b-a229-b10676acf124.png)

Could have specidied that class must exist before student in can be added
Another way is to order creating class before adding student

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: idgrr/ped#11

**Comment by rushilramesh** [comment]
Similar to previous. Need to add class before adding student and reflect accordingly. Inlcude in UG tutorial steps
