### ISSUE TITLE
Incorrect error message for addc

### ISSUE THREAD

**Issue by GabrielWLM** [AY2122S1-CS2103T-W15-1/tp#209]
Need to update User Guide, as well

![image](https://user-images.githubusercontent.com/77065071/140482092-99cfc4ba-e537-47e3-9f49-31e643f5964a.png)

Requirements of command format need to be specified

**Comment by rushilramesh** [comment]
Need to specify format of schedule
Change format of tags 
update ug

**Comment by GabrielWLM** [comment]
![image](https://user-images.githubusercontent.com/77065071/140487244-958e838f-19f7-42f2-a2f3-9d11a83e7baa.png)

add that we don't check the time
Can have negative time periods
