### ISSUE TITLE
Force Capitalisation of ClassCode first letter.

### ISSUE THREAD

**Issue by juliussneezer04** [AY2122S1-CS2103T-W15-1/tp#211]
Duplicate Tutorial Classes with same code, with lower and uppercase difference only.
![image](https://user-images.githubusercontent.com/68603272/140482735-d4695258-3366-4591-9b44-001f6937ce72.png)

**Comment by juliussneezer04** [comment]
Recommended: Disallow use of lowercase 'g' for class code anywhere

**Comment by GabrielWLM** [comment]
![image](https://user-images.githubusercontent.com/77065071/140487244-958e838f-19f7-42f2-a2f3-9d11a83e7baa.png)

can add g00
